#!/bin/bash
# Quick deployment guide for SPIDERWEB

echo "=========================================="
echo "SPIDERWEB - Azure Deployment Guide"
echo "=========================================="
echo ""
echo "You have TWO options to deploy:"
echo ""
echo "OPTION 1: Direct Deployment (Fastest)"
echo "--------------------------------------"
echo "1. Login to Azure:"
echo "   az login"
echo ""
echo "2. Run deployment script:"
echo "   ./deploy-azure.sh"
echo ""
echo "3. Configure API keys after deployment:"
echo "   az containerapp secret set \\"
echo "     --name spiderweb-ml-app-prod \\"
echo "     --resource-group spiderweb-ml-rg \\"
echo "     --secrets openai-api-key=\$OPENAI_API_KEY anthropic-api-key=\$ANTHROPIC_API_KEY"
echo ""
echo ""
echo "OPTION 2: GitHub Actions (For CI/CD)"
echo "--------------------------------------"
echo "1. Create service principal:"
echo "   az login"
echo "   az ad sp create-for-rbac \\"
echo "     --name 'github-actions-spiderweb' \\"
echo "     --role contributor \\"
echo "     --scopes /subscriptions/\$(az account show --query id -o tsv) \\"
echo "     --sdk-auth"
echo ""
echo "2. Add output to GitHub Secret 'AZURE_CREDENTIALS'"
echo "   Go to: https://github.com/deastrobooking/SPIDERWEB/settings/secrets/actions"
echo ""
echo "3. Add API key secrets to GitHub"
echo ""
echo "4. Push code to trigger deployment"
echo ""
echo "=========================================="
echo "For detailed instructions, see:"
echo "- AZURE_AUTH_SETUP.md"
echo "- docs/deployment-azure.md"
echo "- docs/ci-cd-setup.md"
echo "=========================================="
